logging:
  level:
    root: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    cfvbaibai:
      tbourse:
        account:
          storage:
            TransactionMapper: DEBUG

spring:
  datasource:
    schema: classpath:schema-dev.sql
    data: classpath:data-dev.sql
  jpa:
    hibernate:
      ddl-auto: none